import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to
          <Link href="/main">
            <a>Share and vote</a>
          </Link>
        </h1>
        <div className={styles.archi}>
          <Image
            src={"/archi.jpeg"}
            layout="fill"
            objectFit="contain"
            alt="archi"
          />
        </div>
        <h3>The frontend</h3>
        <p>
          {`for the frontend I will use nextjs and redux to manage the state, and
          materialui`}
        </p>
        <h3>The Backend</h3>
        <p>
          {`For the backend, I will use nodejs express js, mongoose , and JWT to
          secure the application. For the database (atlas because it's free),
          we'll need two collections, one for users and one for ideas, when
          someone posts or adds a new idea, he can also add an explanatory file,
          that's why I chose S3 (to store the documents).`}
        </p>
        <h3>next step</h3>
        <p>
          <b>design</b>
          <br />
          <b>CRUDS</b>
          <br />
          <b>PWA</b>
          <br />
          <b>Notification system</b>
          <br />
          <b>Cache</b>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://gaidi-lamjed-web-site-cv.herokuapp.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Gaidi Lamjed IT eng 29/05/2022
        </a>
      </footer>
    </div>
  );
};

export default Home;
